# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-18 17:16
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('webinfo', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='webinfoUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, to=settings.AUTH_USER_MODEL)),
                ('logindate', models.DateField(auto_now=True)),
                ('registerdate', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
